### ISSUE TITLE
Error 400: invalid_request

### ISSUE THREAD

**Issue by stephhlucas** [WPManageNinja/fluent-smtp#88]
You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob

Cannot receive token for FluentSMTP, emails no longer sending. All are erroring

**Comment by siapliw** [comment]
I have the same issue. New set up.
Error 400: invalid_request
You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.
You can let the app developer know that this app doesn't comply with one or more Google validation rules.

**Comment by ashish-patidar-rau** [comment]
I also have same issue, 
is anyone got solution of it.

{
    "error": "invalid_request",
    "error_description": "\nYou can&#39;t sign in to this app because it doesn&#39;t comply with Google&#39;s OAuth 2.0 policy for keeping apps secure.\n\nYou can let the app developer know that this app doesn&#39;t comply with one or more Google validation rules.\n  "
}

**Comment by jvandijk** [comment]
This issue concerns the fact that the strategy has been deprecated by Google : https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#dates-oob

Support thread on the WordPress page : https://wordpress.org/support/topic/google-oauth-oob-flow-warning/

I'm running into this as well, but haven't found an alternative yet.

**Comment by jvandijk** [comment]
I've been able to work around it by changing the strategy to the loopback strategy. Unfortunately that's also deprecated so just a temporary hack.

1. Manually call : https://accounts.google.com/o/oauth2/auth?
	access_type=offline&
	approval_prompt=force&
	redirect_uri=http%3A//127.0.0.1&
	response_type=code&
	scope=https%3A%2F%2Fwww.googleapis.com%2Fauth/gmail.compose&
	client_id=your_client_id
2. The response will fail because it cannot find a local webserver probably, but you can copy the code from the return url
3. Patch the Gmail Handler in the plugin -> fluent-smtp/app/Services/Mailer/Providers/Gmail/Handler.php
4. Change line 144 : `redirect_uri => 'urn:ietf:wg:oauth:2.0:oob'`
5. Into : `'redirect_uri' => 'http://127.0.0.1', 'ack_loopback_shutdown' => '2022-08-31'`
6. Place the copied auth token into the normal FluentSMTP settings strategy and hit save.
7. The plugin will now be able to fetch access & refresh tokens

As said, this is just a temporary solution to still get going with FluentSMTP in combination with Google Workspace.

**Comment by wallenstone** [comment]
+1 on this issue. Was able to work around it using @jvandijk's instructions for now. When is the fix planned?

**Comment by techjewel** [comment]
The issue has been fixed in the latest version.
